name: PapaCaliente
version: '1.0'
main: net.gura.papaCaliente.PapaCaliente
api-version: '1.21'
load: STARTUP
authors: [ Gura ]
depend: [WorldEdit]
description: Plugin Evento Papa Caliente

commands:
  papacaliente:
    description: Inicia o para el evento de papa caliente
    usage: /papacaliente <start|stop>

permissions:
  papacaliente.admin:
    default: op
